language: java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: X1vGxnXTmejcCsVyNC2mijSd+Rze5KE66cxEJ+ILPVqcng9uwp8ff0EeyD3dEipUbE+oUht9LzvouVeq71ESEa93n15eCnGwfA4g+eGMHlZCzO630qzStmg24OOpLsc0R/SZq/zZE3D7KhHhpNdkeqs5zWsQoNYPAAUJSdIX3A+QD8tVOMySzOMmIcueUat1C3snJo99TB3NTwlgb60FLatBzhsmGfWCfy7LPS6TPoteadwqU6n/LOA2+S84J4ci2mvGISD77/jRnkcKGXWHC9PQ2Syk75jiURBzFI3m1Rq6vV2b7OBjVmJOFLvGerTnBXoM8dMKC2fgvQRtl2vSdW2waYwuQf1axjrYTyZN+dE291V1YjaoXrUfNDkvkXdeEe8H2Fn71DIdUy/Ova1FUlosdSBoGlbKoXcuf/ieSxYTG4DMh5zgKg+kQ/Gnh8xJpQnbxGtf10ZKZT1AgbsVtUCB8FjffBfABphJNyB3NDdGPGoECYFpCcaJOmVRlXiBXZ7AqtbqjeRQ5McQkD6x7irV3xdhqbBpVclfgJLmJaxNvauHvwzXCtJ84gKwLCMAxdFGR+x7hcAj180Tr1YYyIxQIoXPeLgtyqF9w4T8v38Nu/MeTkG24weQQHiSFi0IEznVJOOIvxVbjk1jkCVsnDnRoiXJpZZ3gg67c5K/NR8=
  app: bprzybylski-jalgoarena-judge
  on:
    repo: bartpr/JAlgoArena-Judge
